api:
  port: 8080


kafka:
  brokers:
    - kafka:9092
  topic: log-messages
  key: log_collector
  


redis:
  address: redis:6379
  password: ""
  db: 0


# postgres:
#   host: postgres
#   port: 5432
#   user: postgres
#   password: postgres
#   dbname: log_collector


clickhouse:
  host: clickhouse
  port: 9000
  user: clickhouse
  password: clickhouse
  dbname: log_collector