global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']  # Имя сервиса в вашей сети Docker Compose


  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8080']  # Имя сервиса producer в вашей сети Docker Compose

      
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  
